export const LOADING = "LOADING";
export const FAILD = "FAILD";

export const GETALLPRODCUTSSUCCESS = "GETALLPRODCUTSSUCCESS";
export const GETONEPRODCUTSSUCCESS = "GETONEPRODCUTSSUCCESS";

//Add product
export const ADDPRODUCTSUCCESS = "ADDPRODUCTSUCCESS";
// delete product
export const DELETEPRODUCTSUCCESS = "DELETEPRODUCTSUCCESS";
//edit product
export const EDITPRODUCTSUCCESS = "EDITPRODUCTSUCCESS";
